### ISSUE TITLE
Arrange receptor measurements into data tensor

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/FcgR.jl#166]
Let's get the cube assembled.

![Scan3](https://user-images.githubusercontent.com/2065146/78591389-34d21780-77f8-11ea-89b0-5fda50d8c50b.png)

**Comment by murphymadeleine21** [comment]
Trying to figure out the issue with the naming conventions on the luminex file... For example, if we run antigenTables(gp120), it is only going to work for cases like "FcgRI.93TH975.gp120", because gp120 is in the third column. The naming in the luminex file complicates things, because it also has things like "C1q.gp120.RSC3", with "gp120" in the second spot. I think we could change antigen tables to search in all columns (not just the last column) for gp120, but we would need to account for "gp120.something else..." not just gp120 (might be a "contains substring" type function I can find somewhere?). And finally, I think this would cause problems because then we'd have to go through and find all the different antigens possible, and manually call antigen tables for each... Do we have a set list of antigens that we want to have in the cube? Or a possible way to filter these antigens in the luminex file?

**Comment by aarmey** [comment]
It may be easier to simply change the source file. You're absolutely welcome to do so.

**Comment by aarmey** [comment]
I.e. place a different delimiter between antigen and other information.

**Comment by murphymadeleine21** [comment]
Yes, okay. It also seems like the antigens.csv file has a list of antigens–I think this is all of them? In that case, I could change the file on the basis those listed antigens. I think that's the only way I'd really know where to place the different delimiter between antigens.

**Comment by aarmey** [comment]
Yes, I think that’s the list of all antigens.
