### ISSUE TITLE
What do negative weights in the current regression setup mean

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/FcgR.jl#80]
Because effector response should never be protective...

**Comment by cyrillustan** [comment]
According to the current setup, the parameter, λ, for the exponential distribution needs to absorb t_0 and make it 1 (t_0 is the time of the second collection, and its absolute value is unknown).
This means a negative w' * x is valid since its logarithm λ will still be positive.
Negative weight for a cell type looks uncanny. To avoid this issue, a possible solution can be to scratch the logarithm part. Set λ = w' * x directly. Since λ > 0, we will need to set a constraint that every term must be positive.

**Comment by aarmey** [comment]
That sounds like a good plan.

**Comment by cyrillustan** [comment]
changed to positive weights only; already pushed to master branch
